//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace codeChallangeADo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee_Details
    {
        public int Empno { get; set; }
        public string EmpName { get; set; }
        public Nullable<decimal> Empsal { get; set; }
        public string Emptype { get; set; }
    }
}
