//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Booking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Booking()
        {
            this.CancelTickets = new HashSet<CancelTicket>();
        }
    
        public Nullable<int> TrainID { get; set; }
        public string berthType { get; set; }
        public Nullable<int> Totaltickets { get; set; }
        public string BookingStatus { get; set; }
        public Nullable<decimal> payment_amount { get; set; }
        public int BookingID { get; set; }
        public string UserName { get; set; }
    
        public virtual train train { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CancelTicket> CancelTickets { get; set; }
    }
}
