//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelTicket
    {
        public int CancelTicketID { get; set; }
        public Nullable<int> BookingID { get; set; }
        public Nullable<decimal> RefundAmount { get; set; }
        public Nullable<System.DateTime> CancelDate { get; set; }
    
        public virtual Booking Booking { get; set; }
    }
}
