//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MiniProjectAdo
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainBerthInfo
    {
        public Nullable<int> TrainID { get; set; }
        public string BerthClass { get; set; }
        public Nullable<int> TotalSeats { get; set; }
        public Nullable<int> AvailableSeats { get; set; }
        public Nullable<decimal> price { get; set; }
        public int TrainBirthID { get; set; }
    
        public virtual train train { get; set; }
    }
}
